# Generated by Django 4.2.21 on 2025-05-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_panne', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fichier', models.FileField(upload_to='diagnostics/')),
                ('date_diagnostic', models.DateField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.vehicule')),
            ],
        ),
    ]
